### ISSUE TITLE
Build fails with `lists.m2` examples

### ISSUE THREAD

**Issue by seangrate** [Macaulay2/Workshop-2023-Minneapolis#21]
The examples using stuff from `lists.m2` have issues finding the ASMData examples when running `installPackage "MatrixSchubert"`. For example, 
```macaulay2
i1 : ASMFullList(4)
stdio:1:1:(3): error: opening input file "./MatrixSchubert/ASMData/full/4.m2" failed: No such file or directory
```

**Comment by mahrud** [comment]
Maybe try using `currentDirectory()` when loading a file. It depends on the situation though.
