### ISSUE TITLE
LFS data limit

### ISSUE THREAD

**Issue by yuyuan-luo** [Macaulay2/Workshop-2023-Minneapolis#28]
I have a file which is 108MB -- this is the file which contains all the antidiagonal initial ideals for ASM(7). When I try to push via LFS, I get the following error.

`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Not super sure what to do here? I can just keep the file locally/upload to dropbox, but not sure how this would play with future pull request things.

**Comment by mahrud** [comment]
I'm not sure if storing one 108MB file on GitHub makes the most sense. To give you a point of reference, _all packages_ distributed with M2 together currently take about 110MB total, and the largest single file is a 24MB file in the Matroids package. That said, this may be a conversation for the main M2 repository.

Here are a few alternatives to consider:
1. represent the ideals in a more compressed way if possible
2. compress the file (e.g. gzip or bzip2)
3. store the file somewhere else (e.g. a department server or individual repository) and provide a command for downloading it
